# Generated by Django 4.0.5 on 2022-06-23 03:25

from django.db import migrations, models
from datetime import datetime, timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_alter_profile_profil_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now(timezone.utc)),
            preserve_default=False,
        ),
    ]
